- hosts: localhost
  connection: local
  tasks:
    - name: Generate SSH keypair for stack nodes
      command: ssh-keygen -t rsa -b 2048 -f "romana_id_rsa" -N ""
      args:
        creates: "romana_id_rsa"
    - name: Wait for SSH to be ready (controller)
      wait_for: host="{{ hostvars[item].ansible_ssh_host }}" port="{{ hostvars[item].ansible_ssh_port }}"
      with_items: groups.controller | default([])
    - name: Wait for SSH to be ready (computes)
      wait_for: host="{{ hostvars[item].ansible_ssh_host }}" port="{{ hostvars[item].ansible_ssh_port }}"
      with_items: groups.computes | default([])
  
- hosts: stack_nodes
  connection: ssh
  tasks:
    - set_fact:
      args:
        controller_public_ip: "{{ stack_nodes.Controller.mgmt_ip }}"

- include: stack_config.yml
