---
- hosts: devstack_nodes
  roles:
    - stack/devstack/prep

- hosts: devstack_controller
  roles:
    - stack/devstack/install-controller

- hosts: devstack_computes
  roles:
    - stack/devstack/install-compute

- hosts: devstack_controller
  roles:
    - stack/devstack/postinstall
