---
# Ensure stack nodes are ready for installation
- hosts: stack_nodes
  tasks:
    - name: Wait for cloud-init to complete
      wait_for: path="/var/lib/cloud/instance/boot-finished" state=present

# Apply common settings to all nodes prior to installation
- hosts: stack_nodes
  roles:
    - system/ubuntu

# Include stack-specific config stage
- include: "config.{{ stack_type }}.yml"

# Install Romana
- hosts: controller
  roles:
    - romana/install-master

# Include romana+stack playbook
- include: "romana.{{ stack_type }}.yml"

# Install and launch agent (must be after other stages)
- hosts: stack_nodes
  roles:
    - romana/install-agent

# Generate a summary
- hosts: localhost
  roles:
    - summary
