- hosts: localhost
  connection: local
  tasks:
    - name: Check for ec2_id_rsa
      file: path="~/.ssh/ec2_id_rsa" state=file mode=0600
    - name: Generate SSH keypair for stack nodes
      command: ssh-keygen -t rsa -b 2048 -f "romana_id_rsa" -N ""
      args:
        creates: "romana_id_rsa"
    - name: Add Controller host(s)
      add_host: name="{{ item }}" groups="stack_nodes,controllers" ansible_ssh_user="ubuntu" ansible_ssh_private_key_file="~/.ssh/ec2_id_rsa"
      with_items: groups["tag_automation_group_" + devstack_name + "_controller"] | default([])
    - name: Add Compute host(s)
      add_host: name="{{ item }}" groups="stack_nodes,computes" ansible_ssh_user="ubuntu" ansible_ssh_private_key_file="~/.ssh/ec2_id_rsa"
      with_items: groups["tag_automation_group_" + devstack_name + "_compute"] | default([])
    - name: Wait for SSH to be ready (controllers)
      wait_for: host="{{ item }}" port=22
      with_items: groups.controllers | default([])
    - name: Wait for SSH to be ready (computes)
      wait_for: host="{{ item }}" port=22
      with_items: groups.computes | default([])

- hosts: stack_nodes
  connection: ssh
  roles:
    - os-common

- hosts: controllers
  connection: ssh
  roles:
    - stack-controller
    - romana-common
    - romana-master

- hosts: computes 
  connection: ssh
  roles:
    - stack-compute
    - romana-common

- hosts: controllers
  connection: ssh
  roles:
    - romana-demo-setup

- hosts: stack_nodes
  connection: ssh
  roles:
    - romana-agent

- hosts: localhost
  connection: local
  roles:
    - stack-summary
