---
- hosts: kube_nodes
  roles:
    - stack/kubernetes/prep

- hosts: kube_master
  roles:
    - stack/kubernetes/install-master

- hosts: kube_minions
  roles:
    - stack/kubernetes/install-minion

- hosts: kube_master
  roles:
    - stack/kubernetes/postinstall
