---
# Ensure stack nodes are ready for installation
- hosts: stack_nodes
  tasks:
    - name: Wait for cloud-init to complete
      wait_for: path="/var/lib/cloud/instance/boot-finished" state=present
      when: platform == "aws"

# Apply common settings to all nodes prior to installation
- hosts: stack_nodes
  roles:
    - system

# Include stack-specific config stage
- include: "config.{{ stack_type }}.yml"

# Install Romana
- hosts: controller
  roles:
    - romana/install-master
# Stack-specific postinstall after installing master
- include: "post-master.{{ stack_type }}.yml"

# Install and launch agent (must be after other stages)
- hosts: stack_nodes
  roles:
    - romana/install-agent

# Stack-specific postinstall after installing agent
- include: "post-agent.{{ stack_type }}.yml"

# Generate a summary
- hosts: localhost
  roles:
    - summary
