---
- hosts: localhost
  connection: local
  tasks:
    - add_host: name="localhost" groups="aws" ansible_connection=local

- hosts: aws
  roles:
    - provision/generate-ssh-key
    - provision/create-aws-hosts
