---
- hosts: localhost
  connection: local
  tasks:
    - add_host: name="localhost" groups="vagrant" ansible_connection=local
      when: platform == "vagrant"

- hosts: vagrant
  roles:
    - provision/generate-ssh-key
    - provision/create-vagrant-hosts
