---
- hosts: localhost
  connection: local
  tasks:
    - add_host: name="localhost" groups="vagrant" ansible_connection="local"
      when: platform == "vagrant"

- hosts: vagrant
  tasks:
   - name: Destroy VMs
     shell: chdir="{{ stack_data_dir }}" vagrant destroy -f
