---
- hosts: localhost
  tasks:
    - add_host: name="{{ item }}" groups="openstack_nodes,openstack_controller,openstack_computes"
      with_items: "{{ groups.controller }}"
    - add_host: name="{{ item }}" groups="openstack_nodes,openstack_computes"
      with_items: "{{ groups.computes }}"
