---
- hosts: localhost
  tasks:
    - add_host: name="{{ item }}" groups="kube_nodes,kube_master,kube_minions"
      with_items: "{{ groups.controller }}"
    - add_host: name="{{ item }}" groups="kube_nodes,kube_minions"
      with_items: "{{ groups.computes }}"
