---
- hosts: localhost
  tasks:
    - add_host: name="{{ item }}" groups="devstack_nodes,devstack_controller"
      with_items: "{{ groups.controller }}"
    - add_host: name="{{ item }}" groups="devstack_nodes,devstack_computes"
      with_items: "{{ groups.computes }}"
