---
# Install python if it is not avaiable on all nodes prior to installation
- hosts: stack_nodes
  gather_facts: false
  when: ansible_os_family|lower == "debian"
  tasks:
    - raw: (which python && which aptitude) || sudo apt-get update
    - raw: (which python && which aptitude) || sudo apt-get install -y python python-apt aptitude

- hosts: stack_nodes
  gather_facts: false
  when: ansible_os_family|lower == "redhat"
  tasks:
    - raw: which python || sudo yum -y update
    - raw: which python || sudo yum install -y python27
