---
# Install python if it is not avaiable on all nodes prior to installation
- hosts: stack_nodes
  gather_facts: false
  ignore_errors: true
  tasks:
    - raw: (which python && which aptitude) || sudo apt-get update
    - raw: (which python && which aptitude) || sudo apt-get install -y python python-apt aptitude
    - raw: which python || sudo yum -y update
    - raw: which python || sudo yum install -y python27 python-simplejson
    - raw: which python || sudo dnf install -y python2 python2-dnf libselinux-python
