---
- hosts: stack_nodes
  tasks:
    - fail: msg="Unable to determine NIC for network addresses"
      when: ansible_eth1 is not defined and ansible_enp0s8 is not defined
    - name: Normalize the network addresses used by the installer
      set_fact:
        lan_ip:    "{{ ansible_eth1.ipv4.address }}"
        public_ip: "{{ ansible_eth1.ipv4.address }}"
        romana_gw: "{{ romana_cidr | ipsubnet(16, groups.stack_nodes.index(inventory_hostname)) | ipaddr(1) }}"
      when: ansible_eth1 is defined
    - name: Normalize the network addresses used by the installer
      set_fact:
        lan_ip:    "{{ ansible_enp0s8.ipv4.address }}"
        public_ip: "{{ ansible_enp0s8.ipv4.address }}"
        romana_gw: "{{ romana_cidr | ipsubnet(16, groups.stack_nodes.index(inventory_hostname)) | ipaddr(1) }}"
      when: ansible_enp0s8 is defined
