---
- hosts: localhost
  tasks:
    - name: Remove IPs from known_hosts
      when: platform in [ "aws", "vagrant" ]
      known_hosts: host="{{ hostvars[item].ansible_ssh_host }}" state=absent
      with_items: "{{ groups.stack_nodes | default([]) }}"
      failed_when: false
