- hosts: stack_nodes
  connection: ssh
  roles:
    - os-common

- hosts: controller
  connection: ssh
  roles:
    - stack-controller
    - romana-common
    - romana-master

- hosts: computes 
  connection: ssh
  roles:
    - stack-compute
    - romana-common

- hosts: controller
  connection: ssh
  roles:
    - romana-demo-setup

- hosts: stack_nodes
  connection: ssh
  roles:
    - romana-agent

- hosts: localhost
  connection: local
  roles:
    - stack-summary
