- hosts: localhost
  connection: local
  tasks:
    - name: Generate SSH keypair for stack nodes
      command: ssh-keygen -t rsa -b 2048 -f "romana_id_rsa" -N ""
      args:
        creates: "romana_id_rsa"

- hosts: stack_nodes
  connection: ssh
  tasks:
    - name: Wait for cloud-init to complete
      wait_for: path="/var/lib/cloud/instance/boot-finished" state=present

- hosts: stack_nodes
  connection: ssh
  roles:
    - os-common

- hosts: controller
  connection: ssh
  roles:
    - stack-controller
    - romana-common
    - romana-master

- hosts: computes 
  connection: ssh
  roles:
    - stack-compute
    - romana-common

- hosts: controller
  connection: ssh
  roles:
    - romana-demo-setup

- hosts: stack_nodes
  connection: ssh
  roles:
    - romana-agent
