---
- hosts: localhost
  tasks:
    - name: Remove persistent connection sockets, force new connection
      shell: rm -f {{ ansible_user_dir }}/.ansible/cp/ansible-ssh-* &>/dev/null

# Copy clustertests script
- hosts: stack_nodes
  tasks:
    - name: Create cluster-tests directory
      file: path="{{ test_dir }}" state=directory
    - name: Copy test script
      synchronize: src="../test/clustertests" dest="{{ test_script }}"
    - name: Create empty log file
      copy: content='' dest="{{ test_logfile }}" force=yes
       
# Include stack-specific tests, copied then executed
- include: "tests.{{ stack_type }}.yml"
