apiVersion: v1
kind: Service
metadata:
  name: romana-root
  namespace: kube-system
spec:
  ports:
  - name: root
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app: romana-services
  sessionAffinity: None
  type: ClusterIP
