apiVersion: v1
kind: Service
metadata:
  name: romana-root
  namespace: kube-system
spec:
  # This address must be within the service-cluster-ip range
  clusterIP: 100.64.99.99
  ports:
  - name: root
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app: romana-services
  sessionAffinity: None
  type: ClusterIP
