---
apiVersion: v1
kind: Service
metadata:
  name: romana-etcd
  namespace: kube-system
spec:
  clusterIP: 10.96.0.88
  ports:
  - name: etcd
    port: 12379
    protocol: TCP
    targetPort: 12379
  selector:
    romana-app: etcd
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: romana-etcd
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        romana-app: etcd
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      securityContext:
        seLinuxOptions:
          type: spc_t
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: romana-etcd
        image: gcr.io/google_containers/etcd-amd64:3.0.17
        command:
        - etcd
        - "--listen-client-urls=http://0.0.0.0:12379"
        - "--listen-peer-urls=http://127.0.0.1:12380"
        - "--advertise-client-urls=http://10.96.0.88:12379"
        - "--data-dir=/var/etcd/data"
        volumeMounts:
        - name: etcd-data
          mountPath: "/var/etcd/data"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 12379
            host: 127.0.0.1
          initialDelaySeconds: 15
          timeoutSeconds: 15
      volumes:
      - name: etcd-data
        hostPath:
          path: "/var/lib/romana/etcd-db"
