---
- include: config_mysql_{{ ansible_os_family|lower }}.yml
  become: true
  become_user: root

- name: Clone networking-romana repo
  git: repo="{{ romana_networking_repo }}" version="{{ romana_networking_branch }}" dest="/var/tmp/networking-romana" key_file="{{ github_key is defined | ternary('~/.ssh/github_id_rsa', omit) }}" ssh_opts={{ git_ssh_options }} ssh_opts={{ git_ssh_options }}

- name: Install controller local.conf
  template: src="local.conf" dest="~/devstack/local.conf"

- name: Run devstack "stack" script. This may take around 10 minutes.
  shell: ./stack.sh
  args:
    chdir: "~/devstack"
    creates: "~/devstack/stack.sh.log"
  environment:
    CINDER_REPO:       https://github.com/romana-forks/cinder
    GLANCE_REPO:       https://github.com/romana-forks/glance
    HORIZON_REPO:      https://github.com/romana-forks/horizon
    KEYSTONE_REPO:     https://github.com/romana-forks/keystone
    NEUTRON_REPO:      https://github.com/romana-forks/neutron
    NOVA_REPO:         https://github.com/romana-forks/nova
    REQUIREMENTS_REPO: https://github.com/romana-forks/requirements
    NOVNC_REPO:        https://github.com/romana-forks/noVNC
  async: 3600
  poll: 30

- name: Patch in Horizon/UI changes
  patch: src="dashboard_romana_segment.patch" basedir="/opt/stack/horizon" strip=1
  register: p

- include: "{{ file }}"
  with_first_found:
    - files: 
      - "restart_webserver_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "restart_webserver_{{ ansible_distribution|lower }}.yml"
      - "restart_webserver_{{ ansible_os_family|lower }}.yml"
      skip: true
  loop_control:
    loop_var: file
  when: p.changed
  become: true
  become_user: root
