---
- name: Stop Web Server
  become: true
  become_user: root
  service: name="httpd" state="stopped"

- name: Make sure webserver stopped completely
  wait_for: port=80 state=stopped
  when: p.changed

- name: Start Web Server
  become: true
  become_user: root
  service: name="httpd" state="started"
  when: p.changed
