---
- name: etcd binaries
  command: install -o root -g root -m 0755 {{ kubernetes_x_dir }}/etcd-v{{ etcd_version }}-linux-amd64/{{ item }} /usr/local/bin/{{ item }}
  args:
    creates: /usr/local/bin/{{ item }}
  with_items:
    - etcd
    - etcdctl
 
- name: etcd config directory
  file: path="/etc/etcd" state="directory"

- name: etcd config file
  template: src="etcd/etcd.conf" dest="/etc/etcd/etcd.conf"

- name: etcd data dir
  file: path="/var/lib/etcd" state="directory"

- name: kubernetes master config files
  template: src="kubernetes/{{ item }}" dest="/etc/kubernetes/{{ item }}"
  with_items:
    - apiserver
    - scheduler
    - controller-manager

- name: kubernetes binaries
  command: install -o root -g root -m 0755 {{ kubernetes_x_dir }}/kubernetes/server/bin/{{ item }} /usr/local/bin/{{ item }}
  args:
    creates: /usr/local/bin/{{ item }}
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager

- name: Romana-Kubernetes Network Policy service
  command: install -o root -g root -m 0755 {{ kubernetes_x_dir }}/kube/NetworkPolicy/k8s-listener.py /usr/local/lib/romana-kube-np
  args:
    creates: /usr/local/lib/romana-kube-np

- name: Configure IP Address for service
  replace: dest="/usr/local/lib/romana-kube-np" regexp="192\.168\.0\.10" replace="{{ stack_nodes.Controller.mgmt_ip }}"

