---
- name: Create PKI directory
  file: path="/etc/kubernetes/pki" state="directory" mode="0700"
  register: pki

- name: Generate service account keypair
  command: openssl genrsa -out /etc/kubernetes/pki/sa.key 2048
  when: pki.changed

- name: Extract service account public key
  command: openssl rsa -in /etc/kubernetes/pki/sa.key -pubout -out /etc/kubernetes/pki/sa.pub
  when: pki.changed

- name: Install manifests for kubernetes services
  copy: src="manifests/{{ item }}" dest="/etc/kubernetes/manifests/{{ item }}" mode=0600
  with_items:
    - etcd.yaml
    - kube-apiserver.yaml
    - kube-scheduler.yaml
    - kube-controller-manager.yaml

- name: Wait for etcd to be running
  wait_for: host="127.0.0.1" port="2379" state=started
  delegate_to: "{{ inventory_hostname }}"

- name: Wait for apiserver to be running
  wait_for: host="{{ romana_master_ip }}" port="8080" state=started

- name: Copy kube-proxy-daemonset.yml
  copy: src="kube-proxy-daemonset.yml" dest="/var/tmp/kube-proxy-daemonset.yml"

- name: Apply kube-proxy-daemonset
  command: kubectl apply -f "/var/tmp/kube-proxy-daemonset.yml"

- name: Remove taint on master node
  command: kubectl taint nodes --all dedicated-
  ignore_errors: True
