---
- name: Fetch the Kubernetes release
  get_url: url="{{ kubernetes_url }}" checksum="sha1:{{ kubernetes_sha1 }}" dest="{{ kubernetes_dl_dir}}/kubernetes_binaries.tar.bz2" mode=0644
  register: kubedl

- name: Create extraction directory
  file: path="{{ kubernetes_x_dir}}" state="directory"

- name: Extract files
  unarchive: copy=no src="{{ kubernetes_dl_dir}}/kubernetes_binaries.tar.bz2" dest="{{ kubernetes_x_dir}}"
  when: kubedl.changed
