---
- name: Fetch the Kubernetes release
  get_url: url="{{ kubernetes_url }}" dest="{{ kubernetes_dl_dir}}//kubernetes.tar.gz" mode=0644
  register: dl

- name: Validate the downloaded file
  stat: path="{{ kubernetes_dl_dir}}//kubernetes.tar.gz"
  register: k
  when: dl.changed
  failed_when: k.stat.checksum != "{{ kubernetes_sha1 }}"

- name: Extract files (1)
  shell: tar zxvf kubernetes.tar.gz kubernetes/server/kubernetes-server-linux-amd64.tar.gz
  args:
    chdir: "{{ kubernetes_dl_dir}}"
    creates: "{{ kubernetes_x_dir}}/kubernetes/server/kubernetes-server-linux-amd64.tar.gz"
  register: x

# We will copy from this directory in the install-master / install-minion stages
- name: Extract files (2)
  shell: tar zxvf kubernetes/server/kubernetes-server-linux-amd64.tar.gz
  args:
    chdir: "{{ kubernetes_x_dir}}"
  when: x.changed
