---
- include: kube_download.yml
- include: etcd_download.yml

- include: "{{ item }}"
  with_first_found:
    - files: 
      - "packages_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "packages_{{ ansible_distribution|lower }}.yml"
      - "packages_{{ ansible_os_family|lower }}.yml"
      skip: true
  become: true
  become_user: root

- include: "{{ item }}"
  with_first_found:
    - files: 
      - "start_mysql_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "start_mysql_{{ ansible_distribution|lower }}.yml"
      - "start_mysql_{{ ansible_os_family|lower }}.yml"
      skip: true
  become: true
  become_user: root

- include: mysql.yml
  become: true
  become_user: root

- include: kube_files.yml
  become: true
  become_user: root

- include: "service_configs_{{ ansible_service_mgr }}.yml"
  become: true
  become_user: root

- include: start_services.yml
  become: true
  become_user: root
