---
- name: Start etcd
  service: name="etcd" state="started"

- name: Wait for etcd to be available
  wait_for: host="{{ romana_master_ip }}" port=2379

- name: Start kubernetes services
  service: name="{{ item }}" state="started"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
