---
- name: Get devstack
  git: repo="https://github.com/openstack-dev/devstack" version="stable/liberty" dest="~/devstack"

- name: Install controller local.conf
  template: src=local.conf dest="~/devstack/local.conf"

- name: Install extras script that patches nova
  copy: src="../../stack-common/files/nova-patch.sh" dest="~/devstack/extras.d/91-nova-patch.sh" mode=0644

- name: Install the patch that will be applied
  copy: src="../../stack-common/files/romana-nova-reschedule.patch" dest="~/devstack/files/romana-nova-reschedule.patch" mode=0644

- name: Run devstack "stack" script. This may take around 10 minutes.
  shell: chdir="~/devstack" creates="~/devstack/stack.sh.log" ./stack.sh
  async: 3600
  poll: 30
