---
- name: Create Stack with Cloudformation
  cloudformation: stack_name="{{devstack_name}}" region={{region}} disable_rollback=true template="devstack_lite.json"
  args:
     template_parameters:
       KeyName: "{{ key_name }}"
       ControllerInstanceType: "{{ instance_type }}"
       ControllerAMI: "{{ controller_image }}"
       ComputeInstanceType: "{{ instance_type }}"
       ComputeAMI: "{{ compute_image }}"
