---
- name: Install core romana applications for master node
  become: true
  become_user: ubuntu
  include: romana-binaries.yml

- name: Enable romana services for master node
  become: true
  become_user: root
  include: romana-services.yml

- name: Execute romana-master setup
  become: true
  become_user: root
  include: romana-master-setup.yml
