---
- name: Remove if binaries exist
  file: path="{{ romana_dir }}/bin/{{ item }}" state=absent
  with_items:
    - ipam
    - root
    - tenant
    - topology

- name: Download latest binaries
  get_url: url="https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_core_branch }}/{{ item }}" dest="{{ romana_dir }}/bin/{{ item }}" mode=0755
  with_items:
    - ipam
    - root
    - tenant
    - topology
 
- name: Install config file
  template: src="romana.conf.yml" dest="{{ romana_dir }}/etc/romana.conf.yml" mode=0644

# Make sure the bin directory exists
- file: path="/home/ubuntu/bin/" mode=0775 state=directory
# Ensure the jq tool is installed
- apt: pkg="{{ item }}"
  with_items:
    - jq
  become: true
  become_user: root

- name: Install romana tool
  template: src="../cmd/romana" dest="/home/ubuntu/bin/romana" mode=0775
  
