---
- name: Install romana-root upstart service
  template: src="romana-root.conf" dest="/etc/init/romana-root.conf" mode=0644

- name: Launch romana-root
  service: name="romana-root" state="started"

- name: Execute first-run for other services
  shell: "{{ romana_dir }}/bin/{{ item }} -overwriteSchema -rootUrl http://{{ devstack_controller }}:9600"
  with_items:
    - ipam
    - tenant
    - topology

- name: Install other romana upstart services
  template: src="romana-{{ item }}.conf" dest="/etc/init/romana-{{ item }}.conf" mode=0644
  with_items:
    - ipam
    - tenant
    - topology

- name: Restart romana-root
  service: name="romana-root" state="restarted"
  # This brings up the other services also
