---
- name: Install compute local.conf
  template: src=local.conf dest="~/devstack/local.conf"

- name: Run devstack "stack" script. This may take around 5 minutes.
  shell: ./stack.sh
  args:
    chdir: "~/devstack"
    creates: "~/devstack/stack.sh.log"
  environment:
    GIT_BASE: https://github.com/romana
  async: 3600
  poll: 30
