---
- name: Install compute local.conf
  template: src=local.conf dest="~/devstack/local.conf"

- name: Run devstack "stack" script. This may take around 5 minutes.
  shell: ./stack.sh
  args:
    chdir: "~/devstack"
    creates: "~/devstack/stack.sh.log"
  environment:
    NEUTRON_REPO:      https://github.com/romana-forks/neutron
    NOVA_REPO:         https://github.com/romana-forks/nova
    REQUIREMENTS_REPO: https://github.com/romana-forks/requirements
  async: 3600
  poll: 30
