---
kind: Pod
apiVersion: v1
metadata:
  name: romana-mysql
  namespace: kube-system
  labels:
    component: romana-mysql
    tier: control-plane
spec:
  hostNetwork: true
  containers:
  - name: romana-mysql
    image: mysql:5
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: {{ stack_password }}
    volumeMounts:
    - name: mysql-data
      mountPath: "/var/lib/mysql"
  volumes:
  - name: mysql-data
    hostPath:
      path: "/var/lib/romana/mysql-db"
