---
- name: CNI config directory
  file: path="/etc/cni/net.d" state="directory"
  become: true
  become_user: root

- name: CNI config file
  template: src="romana-k8s-network" dest="/etc/cni/net.d/10-romana.conf"
  become: true
  become_user: root

- name: CNI plugin directory
  file: path="/opt/cni/bin" state="directory"
  become: true
  become_user: root

- name: Install CNI plugin executable
  become: true
  become_user: root
  get_url: url=https://raw.githubusercontent.com/romana/core/{{ romana_core_branch }}/pkg/cni/romana dest=/opt/cni/bin/romana mode=0755
  when: romana_core_source == "s3"

- name: CNI plugin tmp directory
  file: path="/var/tmp/cni" state="directory"
  when: romana_core_source == "github"

- name: Download CNI plugin executable from master
  command: rsync -az "{{ romana_master_ip }}:/var/tmp/gopath/src/github.com/romana/core/pkg/cni/romana" "/var/tmp/cni/romana"
  when: romana_core_source == "github"

- name: Install CNI plugin executable
  become: true
  become_user: root
  command: install -o root -g root -m 0755 "/var/tmp/cni/romana" "/opt/cni/bin/romana"
  when: romana_core_source == "github"
