---
- name: Add docker defaults file to add bridge IP option
  copy: src="upstart/defaults_docker" dest="/etc/default/docker"

- name: Install service configurations
  copy: src="upstart/{{ item }}" dest="/etc/init/{{ item }}"
  with_items:
    - kubelet.conf
    - kube-proxy.conf
    - romana-kube-agent.conf
