---
- include: prep_local_registry.yml
  become: true
  become_user: root
  when: romana_core_source == "github"

- name: Install packages required for kubeadm
  include: "{{ file }}"
  with_first_found:
    - files:
      - "packages_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "packages_{{ ansible_distribution|lower }}.yml"
      - "packages_{{ ansible_os_family|lower }}.yml"
      skip: true
  loop_control:
    loop_var: file
  become: true
  become_user: root

- name: Add user to docker group (for convenience, so user can run docker commands)
  become: true
  become_user: root
  user: name="{{ ansible_ssh_user }}" append=yes groups="docker"
