---
- name: Add apt key for packages.cloud.google.com
  become: true
  become_user: root
  apt_key: url="https://packages.cloud.google.com/apt/doc/apt-key.gpg" state="present"

- name: Add Kubernetes apt source
  become: true
  become_user: root
  copy: src="kubernetes.list" dest="/etc/apt/sources.list.d/kubernetes.list"

- include: prep_local_registry.yml
  become: true
  become_user: root
  when: romana_core_source == "github"

- name: Install kubeadm packages
  become: true
  become_user: root
  apt: update_cache="yes" pkg="{{ item }}"
  with_items:
    - docker.io
    - kubelet
    - kubeadm
    - kubernetes-cni

- name: Add user to docker group (for convenience, so user can run docker commands)
  become: true
  become_user: root
  user: name="{{ ansible_ssh_user }}" append=yes groups="docker"
