---
- name: kubeadm init
  become: true
  become_user: root
  command: kubeadm init --token "{{ kubeadm_token }}"

- name: Install kubectl
  become: true
  become_user: root
  apt: pkg="{{ item }}"
  with_items:
    - kubectl
