---
- name: kubeadm init
  become: true
  become_user: root
  shell: |
         if ! [ -d /var/tmp/kubeadm-init ]; then
             kubeadm init --token "{{ kubeadm_token }}" && mkdir /var/tmp/kubeadm-init
         fi

- name: Install kubectl
  become: true
  become_user: root
  apt: pkg="{{ item }}"
  with_items:
    - kubectl
