---
- name: Disable libvirt from being started on installation
  command: printf "manual\n" > /etc/init/libvirt-bin.override
- name: Install libvirt-bin
  apt: pkg="libvirt-bin"
- name: Remove default networks
  file: path="{{ item }}" state=absent
  with_items:
    - "/etc/libvirt/qemu/networks/default.xml"
    - "/etc/libvirt/qemu/networks/autostart/default.xml"
