---
- include: packages.yml
  become: true
  become_user: root

- include: code.yml

- include: pip_cache.yml
  become: true
  become_user: root

- include: disable_virbr0.yml
  become: true
  become_user: root
