apiVersion: v1
kind: Pod
metadata:
  name: nginx-backend
  namespace: tenant-a
  labels:
    app: nginx
    segment: backend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
