apiVersion: v1
kind: Pod
metadata:
  name: nginx-frontend
  namespace: tenant-a
  labels:
    app: nginx
    segment: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
