---
- name: Download binaries
  get_url: url="https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_core_branch }}/{{ item }}" dest="{{ romana_dl_dir }}/{{ item }}" mode=0755
  with_items:
    - ipam
    - root
    - tenant
    - topology
    - romana
    - policy

- name: Install binaries
  become: true
  become_user: root
  command: install -o root -g root -m 0755 "{{ romana_dl_dir }}/{{ item }}" "{{ romana_bin_dir }}/{{ item }}"
  with_items:
    - ipam
    - root
    - tenant
    - topology
    - romana
    - policy
 
- name: Install romana command line config file
  template: src="config/romana.yaml" dest="/home/{{ ansible_ssh_user }}/.romana.yaml" mode=0644
