apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        romana.io/segment: default
    spec:
      containers:
      - name: nginx-default
        image: rstarmer/nginx-curl
        ports:
        - containerPort: 80

