---
- name: kubernetes config directory
  file: path="/etc/kubernetes" state="directory" owner=root group=root

- name: kubernetes config file
  template: src="config" dest="/etc/kubernetes/config"

- name: kubectl
  command: install -o root -g root -m 0755 {{ kubernetes_x_dir }}/kubernetes/server/bin/{{ item }} /usr/local/bin/{{ item }}
  args:
    creates: /usr/local/bin/{{ item }}
  with_items:
    - kubectl
