---
- name: kubelet drop-in path
  become: true
  become_user: root
  file: path="/etc/systemd/system/kubelet.service.d" state="directory" owner=root group=root

- name: kubelet drop-in
  become: true
  become_user: root
  copy: src="10-kubelet-drop-in.conf" dest="/etc/systemd/system/kubelet.service.d/10-kubelet-drop-in.conf" owner=root group=root mode=0600

- name: kubelet config path
  become: true
  become_user: root
  file: path="/etc/kubernetes" state="directory" owner=root group=root

- name: kubelet config
  become: true
  become_user: root
  template: src="kubelet.conf" dest="/etc/kubernetes/kubelet.conf" owner=root group=root mode=0600

- include: "{{ file }}"
  with_first_found:
    - files: 
      - "packages_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}.yml"
      - "packages_{{ ansible_distribution|lower }}.yml"
      - "packages_{{ ansible_os_family|lower }}.yml"
      skip: true
  loop_control:
    loop_var: file
  become: true
  become_user: root

- name: Start services
  become: true
  become_user: root
  service: name="{{ item }}" state="started"
  with_items:
    - docker
    - kubelet

- include: docker_groups.yml
  become: true
  become_user: root

- include: romana_cni.yml
