---
- name: kubernetes config directory
  become: true
  become_user: root
  file: path="/etc/kubernetes" state="directory" owner=root group=root

- name: kubernetes config file
  become: true
  become_user: root
  template: src="config" dest="/etc/kubernetes/config"
