---
- name: Update user profile
  blockinfile:
    dest: "~/.profile"
    block: |
      # Source openstack environment using user=admin and tenant=admin
      . "$HOME/openrc/admin"
  when: ansible_distribution|lower == "ubuntu"

- name: Update user profile
  blockinfile:
    dest: "~/.bash_profile"
    block: |
      # Source openstack environment using user=admin and tenant=admin
      . "$HOME/openrc/admin"
  when: ansible_distribution|lower == "centos"

- name: Install romana post-install script
  template: src="romana-post-install.sh" dest="/var/tmp/romana-post-install.sh" mode=0755

- name: Execute romana post-install script
  shell: /var/tmp/romana-post-install.sh
