---
- name: Fetch calico modified dnsmasq
  get_url: url="https://s3-us-west-1.amazonaws.com/romana-binaries/external/dnsmasq-calico" dest="{{ romana_bin_dir }}/dnsmasq-calico" mode=0755

- name: Create /etc/ethers
  file: path="/etc/ethers" state="touch" mode=0644
