---
# This rule is to ensure DHCP responses can correctly reach the VM instances.
# When passed across the dummy link to the instance's TAP interface, the host kernel doesn't examine the checksum
# but when received by the VM behind that interface, it would be invalid. This rule forces the checksum to be rewritten
- name: UDP Checksum fix
  shell: if ! /sbin/iptables -C {{ item }}; then /sbin/iptables -A {{ item }}; fi
  with_items:
    - POSTROUTING -t mangle -p udp --dport 68 -j CHECKSUM --checksum-fill
