---
- name: Install Agent Proxy Add Policy
  become: true
  become_user: root
  copy: src="agent_proxy_add_policy.sh" dest="{{ romana_bin_dir }}/" mode=0755

- name: Install Agent Proxy Delete Policy
  become: true
  become_user: root
  copy: src="agent_proxy_delete_policy.sh" dest="{{ romana_bin_dir }}/" mode=0755

- name: Install romana command line config file
  template: src="config/romana.yaml" dest="/home/{{ ansible_ssh_user }}/.romana.yaml" mode=0644
