- name: Copy files built on master
  command: rsync -az "{{ romana_master_ip }}:/var/tmp/gopath/bin/{{ item }}" "/var/tmp/{{ item }}"
  with_items:
    - agent
    - romana

- name: Copy policy agent from master
  command: rsync -az "{{ romana_master_ip }}:/var/tmp/gopath/src/github.com/romana/core/pkg/util/policy/agent/agent.py" "/var/tmp/agent.py"

- name: Install files
  become: true
  become_user: root
  command: install -o root -g root -m 0755 "/var/tmp/{{ item }}" "{{ romana_bin_dir }}/{{ item }}"
  with_items:
    - agent
    - romana
    - agent.py
