- name: Copy files built on master
  command: rsync -az "{{ romana_master_ip }}:/var/tmp/gopath/bin/{{ item }}" "/var/tmp/{{ item }}"
  with_items:
    - agent
    - romana

- name: Copy policy-agent from master
  get_url: url=https://raw.githubusercontent.com/romana/core/{{ romana_core_branch }}/pkg/util/policy/agent/agent.py dest=/var/tmp/agent.py mode=0755

- name: Install files
  become: true
  become_user: root
  command: install -o root -g root -m 0755 "/var/tmp/{{ item }}" "{{ romana_bin_dir }}/{{ item }}"
  with_items:
    - agent
    - romana
    - agent.py

- name: Install Agent Proxy Add Policy
  become: true
  become_user: root
  copy: src="agent_proxy_add_policy.sh" dest="{{ romana_bin_dir }}/" mode=0755
  with_items:
    - agent

- name: Install Agent Proxy Delete Policy
  become: true
  become_user: root
  copy: src="agent_proxy_delete_policy.sh" dest="{{ romana_bin_dir }}/" mode=0755

  with_items:
    - agent

- name: Install romana command line config file
  template: src="config/romana.yaml" dest="/home/{{ ansible_ssh_user }}/.romana.yaml" mode=0644
