apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    component: kube-proxy-amd64
    k8s-app: kube-proxy-amd64
    kubernetes.io/cluster-service: "true"
    name: kube-proxy-amd64
    tier: node
  name: kube-proxy-amd64
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: kube-proxy-amd64
      k8s-app: kube-proxy-amd64
      kubernetes.io/cluster-service: "true"
      name: kube-proxy-amd64
      tier: node
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","value":"master","effect":"NoSchedule"}]'
      labels:
        component: kube-proxy-amd64
        k8s-app: kube-proxy-amd64
        kubernetes.io/cluster-service: "true"
        name: kube-proxy-amd64
        tier: node
    spec:
      containers:
      - command:
        - /usr/local/bin/kube-proxy
        - --v=4
        - --kubeconfig=/run/kubeconfig
        image: gcr.io/google_containers/kube-proxy-amd64:v1.4.0
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/run/dbus
          name: dbus
        - mountPath: /run/kubeconfig
          name: kubeconfig
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/kubernetes/kubelet.conf
        name: kubeconfig
      - hostPath:
          path: /var/run/dbus
        name: dbus
